# Generated by Django 3.2.7 on 2022-04-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='search',
            name='images',
            field=models.ImageField(null=True, upload_to='', verbose_name='写真'),
        ),
    ]
