# Generated by Django 3.2.7 on 2022-07-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0002_auto_20220409_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='views',
        ),
    ]
